name: Dev Worflow
 
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
 
jobs:
  health-checkup-job:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: postgres
          MYSQL_DATABASE: django_ci_cd
        ports: ['3306:3306']

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Migrations
        run: python manage.py migrate
        env: 
          APP_DB_ENGINE: django.db.backends.mysql
          APP_DB_NAME: django_ci_cd
          APP_DB_USER: root
          APP_DB_PASSWORD: postgres
          APP_DB_HOST: localhost
          APP_DB_PORT: 3306
      - name: Run Tests
        run: |
          python manage.py test
        env: 
          APP_DB_ENGINE: django.db.backends.mysql
          APP_DB_NAME: django_ci_cd
          APP_DB_USER: root
          APP_DB_PASSWORD: postgres
          APP_DB_HOST: localhost
          APP_DB_PORT: 3306  
      - name: Coverage report
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report --fail-under=75 && coverage xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2